#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/upax_py
  
  rm -rf build/* myApp/* myData/* myU/* uDir/* 
  
  runpysloc -L py check_u_consistency import_u_dir upax_bulk_poster upax_update_node_id  -X cover -X htmlcov -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
