#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/upax_py
  
  rm -rf build/* myApp/* myData/* myU/* uDir/* 
  
  pySloc -L py src tests -X cover -X htmlcov -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
