#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/upax_py
  
  autopep8 -ai -r upax check_u_consistency import_u_dir upax_bulk_poster upax_update_node_id *.py
  echo "not styling dev0/ subdir"
  echo "not styling dev1/ subdir"
  echo "not styling dev2/ subdir"
  echo "not styling dev3/ subdir"
  echo "not styling ndxPages/ subdir"
  echo "not styling sequences/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
