#!/usr/bin/python3

# ~/dev/py/upax/upaxBulkPoster

import os
import re
import sys
import time
from argparse import ArgumentParser

import u
import upax
from xlattice import Q

# PATs AND REs ######################################################


def doWhatever(args):
    noChanges = args.noChanges
    uDir = args.uDir
    usingSHA = args.usingSHA
    verbose = args.verbose

    s = upax.BlockingServer(uDir, usingSHA)
    log = s.log
    if verbose:
        print("there were %7u files in %s at the beginning of the run" % (
            len(log), uDir))

    src = args.pgmNameAndVersion

    files = os.listdir(args.inDir)
    for file in files:
        pathToFile = os.path.join(args.inDir, file)
        if usingSHA == Q.USING_SHA1:
            hash = u.fileSHA1(pathToFile)
        else:
            # FIX ME FIX ME FIX ME
            hash = u.fileSHA3(pathToFile)
        if noChanges:
            if verbose:
                print('would add %s %s' % (hash, pathToFile))
        else:
            s.put(pathToFile, hash, src)

    if verbose:
        print("there are %7u files in %s at the end of the run" % (
            len(log), uDir))
    s.close()


def main():

    pgmNameAndVersion = "upaxBulkPoster v%s %s" % (
        upax.__version__, upax.__version_date__)
    timestamp = "%04d%02d%02d-%02d%02d%02d" % time.gmtime()[:6]

    # -- program defaults -------------------------------------------

    # -- check for config file --------------------------------------

    # -- parse the command line -------------------------------------
    # see docs.python.org/library/argparse.html
    parser = ArgumentParser('post new files in a directory into Upax')

    parser.add_argument('-1', '--usingSHA', action='store_true',
                        help='use SHA1, and so 160-bit keys')

    parser.add_argument('-e', '--ec2Host', action='store_true',
                        help='set if machine is in EC2')

    parser.add_argument('-i', '--inDir', default='NO_SUCH_DIRECTORY',
                        help='path to input directory (forced to ./ testIn if testing)')

    parser.add_argument('-H', '--hostmaster', action='store_true',
                        help='set if machine runs bindMgr')

    parser.add_argument('-j', '--justShow', action='store_true',
                        help='show args and exit')

    parser.add_argument('-N', '--nameserver', action='store_true',
                        help='set if machine is a name server and so runs bindLocalMgr')

    parser.add_argument('-t', '--showTimestamp', action='store_true',
                        help='show run timestamp')

    # just the base name (usually Upax or Upax0) we will fix this up below
    parser.add_argument('-u', '--uDir', default='Upax',
                        help='base name of  U/ directory, default to Upax')

    parser.add_argument('-T', '--testing', action='store_true',
                        help='test run - write to ./testU')

    parser.add_argument('-V', '--showVersion', action='store_true',
                        help='show version number and date')

    parser.add_argument('-v', '--verbose', action='store_true',
                        help='talk a lot')

    parser.add_argument('-z', '--noChanges', action='store_true',
                        help="don't actually write anything to disk")

    args = parser.parse_args()      # a Namespace object

    # -- fixups -----------------------------------------------------
    args.pgmNameAndVersion = pgmNameAndVersion
    if args.testing:
        args.inDir = 'testIn'
    args.timestamp = timestamp

    # -- sanity checks ----------------------------------------------
    if not os.path.exists(args.inDir):
        print("input directory '%s' does not exist" % args.inDir)
        sys.exit(1)

    # REMOVING THIS RESTRICTION #################
#   uDirParts = args.uDir.split('/')
#   if len(uDirParts) > 1:
#       print "uDir may not contain any slashes: aborting"
#       sys.exit(1)

    if args.hostmaster and args.nameserver:
        print('you cannot select both hostmaster and nameserver attributes')
        sys.exit(1)

    # fixups --------------------------------------------------------
    args.pgmNameAndVersion = pgmNameAndVersion
    if args.uDir and args.uDir[-1] == '/':
        args.uDir = args.uDir[:-1]          # drop any trailing slash

    if args.testing:
        args.uDir = 'testU'
    elif args.ec2Host:
        args.uDir = os.path.join('/vol', args.uDir)
    else:
        args.uDir = os.path.join('/var', args.uDir)

    # -- do it ------------------------------------------------------
    if args.verbose or args.showVersion or args.justShow:
        print(args.pgmNameAndVersion)
    if args.showTimestamp:
        print('run at %s GMT' % timestamp)   # could be prettier
    else:
        print()                               # there's a comma up there

    if args.justShow or args.verbose:
        print('hostmaster       = ' + str(args.hostmaster))
        print('inDir            = ' + str(args.inDir))
        print('justShow         = ' + str(args.justShow))
        print('nameserver       = ' + str(args.nameserver))
        print('noChanges        = ' + str(args.noChanges))
        print('showTimestamp    = ' + str(args.showTimestamp))
        print('showVersion      = ' + str(args.showVersion))
        print('testing          = ' + str(args.testing))
        print('timestamp        = ' + str(args.timestamp))
        print('usingSHA        = ' + str(args.usingSHA))
        print('uDir             = ' + str(args.uDir))
        print('verbose          = ' + str(args.verbose))

    if not args.justShow:
        lock = u.ULock(args.uDir)
        try:
            if lock.getLock():
                doWhatever(args)
            else:
                print('could not get lock on %s' % args.uDir)
        finally:
            lock.releaseLock()

if __name__ == '__main__':
    main()
