[meta]
version = "0.1.0"

[project]
name = "upax_py"
package = "upax"
main_lang = "py"
version = "0.10.0"
version_date = "2018-01-31"
author = "Jim Dixon"
author_email = "jdd@gmail.com"
description = "full-mesh ring of U store servers"
copyright = "2012-2017"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/upax_py"
state = "shared"
url = "https://jddixon.github.io/upax_py"

[py]
packages = [ "upax",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = [ "src/check_u_consistency", "src/import_u_dir", "src/upax_bulk_poster", "src/upax_update_node_id",]
ext_modules = []
distshare = [ "optionz", "rnglib", "xlattice_py",]
requirements = [ "pycrypt", "scandir", "setuptools",]
test_requirements = [ "pyzmq",]
